language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
  - "pypy" # Run slowest last
  - "pypy3"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8 soco
  - pylint soco
  - py.test --cov-config .coveragerc --cov soco .

after_script:
  - coveralls

sudo: false
